image:
  tag: "0.1.14"

secret:
  name: "api-credentials"
  useExistingSecret: true

configMap:
  annotations: {}
  config: |-
    resources: # List of K8s resources to list, watch, and export to Port.
      - kind: apps/v1/replicasets # group/version/resource (G/V/R) format
        selector:
          query: .metadata.namespace | startswith("kube") | not # JQ boolean query. If evaluated to false - skip syncing the object.
        port:
          entity:
            mappings: # Mappings between one K8s object to one or many Port Entities. Each value is a JQ query.
              - identifier: .metadata.name
                title: .metadata.name
                blueprint: '"deploymentConfig"'
                properties:
                  creationTimestamp: .metadata.creationTimestamp
                  annotations: .metadata.annotations
                  status: .status
  name: "port-k8s-exporter"
  create: true

serviceAccount:
  create: true
  annotations: {}
  name: "port-k8s-exporter"

clusterRole:
  name: "port-k8s-exporter"
  apiGroups:
    - "'*'"
  resources:
    - "'*'"
    ## TODO: restrict to only the verbs needed, remove secrets get\list\watch
  verbs:
    - "'get'"
    - "'list'"
    - "'watch'"
clusterRoleBinding:
  name: "port-k8s-exporter"
