---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
    - ../../bases/helm

labels:
    - includeSelectors: true
      pairs:
          app.kubernetes.io/managed-by: argocd

patches:
    - target:
          group: argoproj.io
          version: v1alpha1
          kind: Application
      patch: |-
          - op: add
            path: /spec/source/helm/valueFiles/-
            value: values-platform-dev.yaml
          - op: add
            path: /metadata/labels/environment
            value: platform-dev